routes/web.php
<?php

Route::get('/', 'HomeController@index')->name('home');

Route::middleware(['admin'])->group(function () {
    Route::prefix('admin')->name('admin.')->group(function () {
        Route::get('/', 'Admin\IndexController@index')->name('index');

        Route::resource('/todo', 'Admin\TodoController');
        Route::resource('/user', 'Admin\UserController');
    });
});


Auth::routes();

resources/views/layout/admin/app.blade.php
<!doctype html>
    <html lang="en">
    <head>
        @include('layout.admin.head')
    </head>
    <body>
        @yield('content')
        @include('layout.admin.footer')
    </body>
</html>

resources/views/layout/admin/footer.blade.php
<footer style="margin: 60px 0">
    <div class="container">
        <div class="row">
            <div class="col">

            </div>
        </div>
    </div>
</footer>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

@yield('script')

resources/views/layout/admin/head.blade.php
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="csrf-token" content="{{ csrf_token() }}">
<title>{{ $meta['title'] }}</title>

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
<link rel="stylesheet" href="/css/admin.css">

resources/views/layout/admin/header.blade.php
<div class="container">
    <div class="row">
        <div class="col header">
            <h1>{{ $meta['title'] }} {!! isset($header) ? $header : '' !!}</h1>
        </div>
    </div>
</div>

@include('layout.partials.flash')

resources/views/layout/admin/sidebar.blade.php
<div class="col-lg-3">
    <ul class="list-group">
        <li class="list-group-item">
            <ul class="list-unstyled">
                <li><a href="{{ route('admin.index') }}">Админпанель</a></li>
                <li><a href="{{ route('home') }}">На сайт</a></li>
            </ul>
        </li>
        <li class="list-group-item">
            <h5>Задачи</h5>
            <ul class="list-group-sublist">
                <li><a href="{{ route('admin.todo.index') }}">Все задачи</a></li>
            </ul>
        </li>
        <li class="list-group-item">
            <h5>Пользователи</h5>
            <ul class="list-group-sublist">
                <li><a href="{{ route('admin.user.index') }}">Все пользователи</a></li>
            </ul>
        </li>
    </ul>
</div>