routes/web.php
<?php

Route::get('/', 'HomeController@index')->name('home');

Route::middleware(['admin'])->group(function () {
    Route::prefix('admin')->name('admin.')->group(function () {
        Route::get('/', 'Admin\IndexController@index')->name('index');

        Route::resource('/todo', 'Admin\TodoController');
        Route::resource('/user', 'Admin\UserController');
    });
});


Auth::routes();

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * @var array
     */
    protected $guarded = ['id', 'created_at', 'updated_at'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Массив с дежурными сообщениями о результате выполненной операции
     * @var array
     */
    public static $alerts = [
        'success_create' => 'Пользователь успешно добавлен!',
        'error_create' => 'Пользователь не был добавлен!',
        'success_update' => 'Пользователь успешно отредактирован!',
        'error_update' => 'Пользователь не был отредактирован!',
        'success_destroy' => 'Пользователь успешно удалён!',
        'error_destroy' => 'Пользователь не был удалён!',
    ];

    /**
     * @return HasMany
     */
    public function todos()
    {
        return $this->hasMany(Todo::class);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\UserRequest;
use App\Models\User;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Routing\Redirector;
use Illuminate\View\View;

class UserController extends BaseController
{
    /**
     * UserController constructor.
     */
    public function __construct()
    {
        parent::__construct(User::class, [
            'index' => 'Все пользователи',
            'create' => 'Создать пользователя',
            'edit' => 'Отредактировать пользователя',
        ], 'user');
    }


    /**
     * @param  int  $id
     * @param  array|null  $additionalParams
     * @return Factory|View
     */
    public function edit(int $id, ?array $additionalParams = [])
    {
        return parent::edit($id, $additionalParams);
    }

    /**
     * @param  UserRequest  $request
     * @return RedirectResponse|Redirector
     */
    public function store(UserRequest $request)
    {
        return parent::_store($request);
    }

    /**
     * @param  UserRequest  $request
     * @param  int  $id
     * @return RedirectResponse|Redirector
     */
    public function update(UserRequest $request, int $id)
    {
        return parent::_update($request, $id);
    }
}

app/Http/Controllers/Api/UserController.php
<?php

namespace App\Http\Controllers\Api;

use App\Api\Transformers\FactoryTransformers;
use App\Models\User;
use App\Repositories\Contract\Repository;
use App\Repositories\Factory\RepositoryFactory;
use Exception;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

/**
 * Class UserController
 * @package App\Http\Controllers\Api
 */
class UserController extends ApiController
{

    /**
     * @var Repository
     */
    private $userRepo;

    /**
     * UserController constructor.
     */
    public function __construct()
    {
        $this->userRepo = RepositoryFactory::make(User::class);
    }

    /**
     * @param  Request  $request
     * @return JsonResponse
     * @throws Exception
     */
    public function getAll(Request $request)
    {
        $input = $request->all();

        if (!$input) {
            return $this->respondBadRequest();
        }

        $token = filter_var($input['api_token'] ?? '', FILTER_SANITIZE_STRING);

        if (!$token) {
            return $this->respondUnauthorized();
        }

        $users = $this->userRepo->getAll()->get()->toArray();

        if (!$users) {
            return $this->respondNotFound('User has not been found!');
        }

        $items = FactoryTransformers::make('user')->transformCollection($users);

        return $this->respond([
            'response' => [
                'items' => $items,
                'count' => count($users)
            ]
        ]);
    }
}

resources/views/admin/user/create.blade.php
@extends('layout.admin.app')

@section('content')

    @include('layout.admin.header')

    <div class="container" id="app">
        <div class="row">
            @include('layout.admin.sidebar')
            <div class="col-lg-9">
                @include('admin.user.form')
            </div>
        </div>
    </div>
@stop

@section('script')
    <script src="/js/admin.js"></script>
    <script>
        let tokenUpdateBtn = document.querySelector('#token_update_btn');

        tokenUpdateBtn.addEventListener('click', (event) => {
            event.preventDefault();

            let oldTokenInput = document.querySelector('input[name="api_token"]');

            $.ajax({
                url: "/api/update-token",
                type: "get",
                data: {
                    'api_token': oldTokenInput.value,
                },
                success: (response) => {
                    let result = response['response'];
                    if (! result) { return; }

                    console.log(result['api_token']);

                    oldTokenInput.value = result['api_token'];
                },
                error: (xhr) => {

                }
            });
        });

    </script>
@stop

resources/views/admin/user/form.blade.php
@if(isset($data))
    {{ Form::model($data, ['url' => route('admin.user.update', [$data->id]), 'method' => 'patch']) }}
@else
    {{ Form::open(['url' => route('admin.user.store'), 'method' => 'post']) }}
@endif

    <div class="row">
        <div class="col-sm-6">
            @include('forms.admin.text', ['key' => 'name', 'label' => 'Имя'])
        </div>

        <div class="col-sm-6">
            @include('forms.admin.email', ['key' => 'email', 'label' => 'E-mail'])
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            @include('forms.admin.disables_text', ['key' => 'api_token', 'label' => 'API токен'])
        </div>
    </div>

    <div class="form-group">
        <input type="submit" value="Отправить" class="btn btn-primary">
    </div>

{{ Form::close() }}

resources/views/admin/user/index.blade.php
@extends('layout.admin.app')

@section('content')

    @include('layout.admin.header')

    <div class="container">
        <div class="row">
            @include('layout.admin.sidebar')
            <div class="col-lg-9">
                @if($data->isNotEmpty())
                    @foreach($data as $item)
                        <div class="category">
                            <a href="{{ route('admin.user.edit', [$item->id]) }}">
                                {{ $item->name }} [id: {{ $item->id }}]
                            </a>
                            <a href="{{ route('admin.user.destroy', [$item->id]) }}" data-method="delete" data-token="{{ csrf_token() }}" data-confirm="Удалить?">Удалить</a>
                        </div>
                        <hr />
                    @endforeach

                    {{ $data->render() }}
                @else
                    <p>Список пуст.</p>
                @endif
            </div>
        </div>
    </div>
@stop

@section('script')
    <script src="/js/admin.js"></script>
@stop